### PR TITLE
Enhancements to create topic and subscription

### PR DESCRIPTION
**Pull request by johnrhampton**
- Handles Subscription exists error

- Adds comments to create topic

### CODE REVIEW

**Review by jsrhodes15 — APPROVED** [review]

**Comment by johnrhampton** [comment]
@jsrhodes15 any objections if I publish this latest version?

**Comment by jsrhodes15** [comment]
Nope none at all. I should have done that. Forgot. Sorry.

**Comment by johnrhampton** [comment]
no worries at all.. will publish this afternoon.

**Comment by johnrhampton** [comment]
@jsrhodes15 could you please publish the latest or add me as an owner - I'm not able to publish right now.  `npm owner add <user> [<@scope>/]<pkg>`

**Pull request merged**
