### PR TITLE
Cut One - Generic Scripts

### PR DESCRIPTION
**Pull request by johnrhampton**
Makes the scripts generic so they can be consumed by any node process.

Standardizes the script pattern.

Adds subscriptionDetails script.

Adds basic validation library to reduce common code.

Adds a couple examples of how to use 2 scripts.

### CODE REVIEW

**Review by jsrhodes15 — APPROVED** [review]
Approving mostly out of trust. I know this is the way we want to go for sure.

**Comment by johnrhampton** [comment]
@jsrhodes15 want me to merge?

**Comment by jsrhodes15** [comment]
@johnrhampton Yeah go ahead. I would like to see Chuck approve as well, since I don't have insight into the direction/patterns that the two of you spoke of. But I wouldn't hold up this PR.

**Comment by johnrhampton** [comment]
right on.. happy to make any subsequent changes if we all decide the patterns need adjustments

**Pull request merged**
